<?php

/**
 * @file
 * Contains multistep.module.
 */

use Drupal\Core\Form\FormStateInterface;
//use Drupal\multistep\Controller\MultistepController;


// /**
// * Implementation of hook_form_FORM_ID_alter().
// */
// function multistep_form_alter(&$form, FormStateInterface &$form_state) {
//   //$form['mail']['#title'] = t('email');
// }

function multistep_theme($existing, $type, $theme, $path) {
    return [
        'course_list'  => [ 
            'variables' => [
                'grade' => NULL,
                'results' => NULL
            ],

    ]];
}