<?php

/**
 * @file
 * Contains multistep.module.
 */

use Drupal\Core\Form\FormStateInterface;
//use Drupal\multistep\Controller\MultistepController;


// /**
// * Implementation of hook_form_FORM_ID_alter().
// */
function multistep_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
   // $form['#attached']['library'][] = '/multistep/multistep_form';
 }

function multistep_theme($existing, $type, $theme, $path) {
    $n = 12;
    return [
        'course_list'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_math'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_ss'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_sci'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_pe'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_vapa'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_lang'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_health'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_cpe'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_elec'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

        'course_list_health'  => [ 
            'variables' => [
                'grade' => NULL,
                'isAP' =>  NULL,
                'isFund' => NULL,
                'isELD' => NULL,
                'results' => NULL,
                'subject' => NULL,
                'n' => $n
            ]
        ],

    ];
}

